name: Nekontrol package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    name: Lint and format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install compilers
        run: |
          sudo apt install luajit nodejs rustc gcc ghc python3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Run tests
        run: |
          poetry run pytest . -v

  typecheck:
    name: Typecheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Set up pyright
        run: |
          sudo apt install nodejs
          npm install -g pyright

      - name: Type check
        run: |
          pyright --pythonpath "$(poetry env info --path)/bin/python" --warnings

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --without dev

      - name: Test building
        run: |
          poetry build
